//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compiler.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string AboutProgramItemHeader {
            get {
                return ResourceManager.GetString("AboutProgramItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display information about program.
        /// </summary>
        public static string AboutProgramItemHeaderDescription {
            get {
                return ResourceManager.GetString("AboutProgramItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis method.
        /// </summary>
        public static string AnalysisMethodMenuItemHeader {
            get {
                return ResourceManager.GetString("AnalysisMethodMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected assignment operator.
        /// </summary>
        public static string AssignmentOperatorExpected {
            get {
                return ResourceManager.GetString("AssignmentOperatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliography.
        /// </summary>
        public static string BibliographyMenuItemHeader {
            get {
                return ResourceManager.GetString("BibliographyMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call docs.
        /// </summary>
        public static string CallDocsItemHeader {
            get {
                return ResourceManager.GetString("CallDocsItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display documentation window.
        /// </summary>
        public static string CallDocsItemHeaderDescription {
            get {
                return ResourceManager.GetString("CallDocsItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected const keyword.
        /// </summary>
        public static string ConstKeywordExpected {
            get {
                return ResourceManager.GetString("ConstKeywordExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyMenuItemHeader {
            get {
                return ResourceManager.GetString("CopyMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected text to the clipboard.
        /// </summary>
        public static string CopyMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("CopyMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateMenuItemHeader {
            get {
                return ResourceManager.GetString("CreateMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new file.
        /// </summary>
        public static string CreateMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("CreateMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutMenuItemHeader {
            get {
                return ResourceManager.GetString("CutMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected text and copy it to the clipboard.
        /// </summary>
        public static string CutMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("CutMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string DecreaseTextSizeMenuItemHeader {
            get {
                return ResourceManager.GetString("DecreaseTextSizeMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuItemHeader {
            get {
                return ResourceManager.GetString("DeleteMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected text.
        /// </summary>
        public static string DeleteMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("DeleteMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic and neutralization of errors.
        /// </summary>
        public static string DiagnosticNeutralizationMenuItemHeader {
            get {
                return ResourceManager.GetString("DiagnosticNeutralizationMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        public static string DocsItemHeader {
            get {
                return ResourceManager.GetString("DocsItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        public static string DocsWindowTitle {
            get {
                return ResourceManager.GetString("DocsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditMenuItemHeader {
            get {
                return ResourceManager.GetString("EditMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ErrorsDescriptionColumn {
            get {
                return ResourceManager.GetString("ErrorsDescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ErrorsPositionColumn {
            get {
                return ResourceManager.GetString("ErrorsPositionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string ErrorsTab {
            get {
                return ResourceManager.GetString("ErrorsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitMenuItemHeader {
            get {
                return ResourceManager.GetString("ExitMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close text editor.
        /// </summary>
        public static string ExitMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("ExitMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenuItemHeader {
            get {
                return ResourceManager.GetString("FileMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix.
        /// </summary>
        public static string FixMenuItemHeader {
            get {
                return ResourceManager.GetString("FixMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification of grammar.
        /// </summary>
        public static string GrammarClassificationMenuItemHeader {
            get {
                return ResourceManager.GetString("GrammarClassificationMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar.
        /// </summary>
        public static string GrammarMenuItemHeader {
            get {
                return ResourceManager.GetString("GrammarMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected identifier.
        /// </summary>
        public static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        public static string IncreaseTextSizeMenuItemHeader {
            get {
                return ResourceManager.GetString("IncreaseTextSizeMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected link.
        /// </summary>
        public static string LinkExpected {
            get {
                return ResourceManager.GetString("LinkExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing expected.
        /// </summary>
        public static string NothingExpected {
            get {
                return ResourceManager.GetString("NothingExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenMenuItemHeader {
            get {
                return ResourceManager.GetString("OpenMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open new file.
        /// </summary>
        public static string OpenMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("OpenMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected operator end.
        /// </summary>
        public static string OperatorEndExpected {
            get {
                return ResourceManager.GetString("OperatorEndExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse errors.
        /// </summary>
        public static string ParseErrorsTab {
            get {
                return ResourceManager.GetString("ParseErrorsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteMenuItemHeader {
            get {
                return ResourceManager.GetString("PasteMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste text from the clipboard at the current cursor position.
        /// </summary>
        public static string PasteMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("PasteMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulation of problem.
        /// </summary>
        public static string ProblemFormulationMenuItemHeader {
            get {
                return ResourceManager.GetString("ProblemFormulationMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RedoMenuItemHeader {
            get {
                return ResourceManager.GetString("RedoMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo last undone action.
        /// </summary>
        public static string RedoMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("RedoMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunMenuItemHeader {
            get {
                return ResourceManager.GetString("RunMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string SaveAsMenuItemHeader {
            get {
                return ResourceManager.GetString("SaveAsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current file under a new name.
        /// </summary>
        public static string SaveAsMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("SaveAsMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SaveDialogCancel {
            get {
                return ResourceManager.GetString("SaveDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes you made to {0}?.
        /// </summary>
        public static string SaveDialogContentHeader {
            get {
                return ResourceManager.GetString("SaveDialogContentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save.
        /// </summary>
        public static string SaveDialogDontSave {
            get {
                return ResourceManager.GetString("SaveDialogDontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveDialogSave {
            get {
                return ResourceManager.GetString("SaveDialogSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes will be lost if you don&apos;t save them..
        /// </summary>
        public static string SaveDialogSupportingText {
            get {
                return ResourceManager.GetString("SaveDialogSupportingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string SaveFilePickerTitle {
            get {
                return ResourceManager.GetString("SaveFilePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveMenuItemHeader {
            get {
                return ResourceManager.GetString("SaveMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current file.
        /// </summary>
        public static string SaveMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("SaveMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAllMenuItemHeader {
            get {
                return ResourceManager.GetString("SelectAllMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all text.
        /// </summary>
        public static string SelectAllMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("SelectAllMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to separator expected.
        /// </summary>
        public static string SeparatorExpected {
            get {
                return ResourceManager.GetString("SeparatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string SourceCodeMenuItemHeader {
            get {
                return ResourceManager.GetString("SourceCodeMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected string literal.
        /// </summary>
        public static string StringLiteralExpected {
            get {
                return ResourceManager.GetString("StringLiteralExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected str type.
        /// </summary>
        public static string StrTypeExpected {
            get {
                return ResourceManager.GetString("StrTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text example.
        /// </summary>
        public static string TextExampleMenuItemHeader {
            get {
                return ResourceManager.GetString("TextExampleMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextMenuItemHeader {
            get {
                return ResourceManager.GetString("TextMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size.
        /// </summary>
        public static string TextSizeMenuItemHeader {
            get {
                return ResourceManager.GetString("TextSizeMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier can only start with a number.
        /// </summary>
        public static string TokenErrorIdentifierCanOnlyStartWithALetter {
            get {
                return ResourceManager.GetString("TokenErrorIdentifierCanOnlyStartWithALetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected symbol(s).
        /// </summary>
        public static string TokenErrorUnexpectedSymbol {
            get {
                return ResourceManager.GetString("TokenErrorUnexpectedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string.
        /// </summary>
        public static string TokenErrorUnterminatedString {
            get {
                return ResourceManager.GetString("TokenErrorUnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string TokensCodeColumn {
            get {
                return ResourceManager.GetString("TokensCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string TokensPositionColumn {
            get {
                return ResourceManager.GetString("TokensPositionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens.
        /// </summary>
        public static string TokensTab {
            get {
                return ResourceManager.GetString("TokensTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string TokensTokenColumn {
            get {
                return ResourceManager.GetString("TokensTokenColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TokensTypeColumn {
            get {
                return ResourceManager.GetString("TokensTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenTypeCloseBracket.
        /// </summary>
        public static string TokenTypeCloseBracket {
            get {
                return ResourceManager.GetString("TokenTypeCloseBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fn end token.
        /// </summary>
        public static string TokenTypeCloseFnBody {
            get {
                return ResourceManager.GetString("TokenTypeCloseFnBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon.
        /// </summary>
        public static string TokenTypeColon {
            get {
                return ResourceManager.GetString("TokenTypeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comma token.
        /// </summary>
        public static string TokenTypeComma {
            get {
                return ResourceManager.GetString("TokenTypeComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fn keyword.
        /// </summary>
        public static string TokenTypeFnKeyword {
            get {
                return ResourceManager.GetString("TokenTypeFnKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; token.
        /// </summary>
        public static string TokenTypeGreater {
            get {
                return ResourceManager.GetString("TokenTypeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i32 keyword.
        /// </summary>
        public static string TokenTypeI32Keyword {
            get {
                return ResourceManager.GetString("TokenTypeI32Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string TokenTypeIdentifier {
            get {
                return ResourceManager.GetString("TokenTypeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - token.
        /// </summary>
        public static string TokenTypeMinus {
            get {
                return ResourceManager.GetString("TokenTypeMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( token.
        /// </summary>
        public static string TokenTypeOpenBracket {
            get {
                return ResourceManager.GetString("TokenTypeOpenBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fn start token.
        /// </summary>
        public static string TokenTypeOpenFnBody {
            get {
                return ResourceManager.GetString("TokenTypeOpenFnBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return keyword.
        /// </summary>
        public static string TokenTypeReturnKeyword {
            get {
                return ResourceManager.GetString("TokenTypeReturnKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; token.
        /// </summary>
        public static string TokenTypeSemiColon {
            get {
                return ResourceManager.GetString("TokenTypeSemiColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        public static string TokenTypeSeparator {
            get {
                return ResourceManager.GetString("TokenTypeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string ToolbarAboutProgram {
            get {
                return ResourceManager.GetString("ToolbarAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call docs.
        /// </summary>
        public static string ToolbarCallDocs {
            get {
                return ResourceManager.GetString("ToolbarCallDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ToolbarCopy {
            get {
                return ResourceManager.GetString("ToolbarCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file.
        /// </summary>
        public static string ToolbarCreate {
            get {
                return ResourceManager.GetString("ToolbarCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string ToolbarCut {
            get {
                return ResourceManager.GetString("ToolbarCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix.
        /// </summary>
        public static string ToolbarFix {
            get {
                return ResourceManager.GetString("ToolbarFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string ToolbarOpen {
            get {
                return ResourceManager.GetString("ToolbarOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string ToolbarPaste {
            get {
                return ResourceManager.GetString("ToolbarPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string ToolbarRedo {
            get {
                return ResourceManager.GetString("ToolbarRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string ToolbarRun {
            get {
                return ResourceManager.GetString("ToolbarRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string ToolbarSave {
            get {
                return ResourceManager.GetString("ToolbarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string ToolbarUndo {
            get {
                return ResourceManager.GetString("ToolbarUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected type divider.
        /// </summary>
        public static string TypeDividerExpected {
            get {
                return ResourceManager.GetString("TypeDividerExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoMenuItemHeader {
            get {
                return ResourceManager.GetString("UndoMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last action.
        /// </summary>
        public static string UndoMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("UndoMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled {0}.
        /// </summary>
        public static string UntitledFileName {
            get {
                return ResourceManager.GetString("UntitledFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WindowWarningTitle {
            get {
                return ResourceManager.GetString("WindowWarningTitle", resourceCulture);
            }
        }
    }
}
